# Generated by Django 6.0.6 on 2026-07-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_name',
            field=models.BooleanField(default=True),
        ),
    ]
