# Generated by Django 6.0.6 on 2026-07-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_iban_customuser_sub_merchant_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sub_merchant_key',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tckn',
        ),
    ]
