# Generated by Django 6.0.6 on 2026-07-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_booking_deposit_price_booking_handover_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='handover_photos',
            field=models.ImageField(blank=True, null=True, upload_to='handover_photos/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_photos',
            field=models.ImageField(blank=True, null=True, upload_to='return_photos/'),
        ),
    ]
