# Generated by Django 6.0.6 on 2026-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_message_is_offer_message_offer_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
