# Generated by Django 6.0.6 on 2026-07-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_item_banned_until_item_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='full_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
