# Generated by Django 6.0.6 on 2026-07-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_item_full_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='full_address',
            field=models.TextField(blank=True, null=True, verbose_name='Açık Adres (Cadde/Sokak/No)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mahalle / Semt'),
        ),
    ]
