# Generated by Django 6.0.6 on 2026-07-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_item_full_address_alter_item_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_location_share',
            field=models.BooleanField(default=False, verbose_name='Konum Paylaşımı mı?'),
        ),
        migrations.AddField(
            model_name='message',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Açık Adres / Yer İsmi'),
        ),
        migrations.AddField(
            model_name='message',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem'),
        ),
        migrations.AddField(
            model_name='message',
            name='location_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam'),
        ),
    ]
