# Generated by Django 6.0.6 on 2026-07-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_item_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dispute_winner',
            field=models.CharField(blank=True, choices=[('owner', 'Satıcı Haklı (Depozito Satıcıda Kalır)'), ('renter', 'Kiracı Haklı (Depozito İade Edilir)'), ('draw', 'Berabere / Kısmi')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='handover_notes',
            field=models.TextField(blank=True, help_text='Kiracının ürünü alırken bıraktığı not', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_notes',
            field=models.TextField(blank=True, help_text='Satıcının ürünü iade alırken bıraktığı not', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dispute_reason',
            field=models.TextField(blank=True, help_text='İtiraz edilirse sebebi', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Onay Bekliyor (Para Havuzda)'), ('approved', 'Onaylandı (Bekleniyor)'), ('handover_pending', 'Satıcı Teslimat Onayı Bekliyor'), ('active', 'Kirada (Teslim Edildi)'), ('return_pending', 'Kiracı İade Onayı Bekliyor'), ('completed', 'Tamamlandı (İade Edildi)'), ('rejected', 'Reddedildi / İptal'), ('disputed', 'Uyuşmazlık (Sorun Var)')], default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingimage',
            name='image_type',
            field=models.CharField(choices=[('handover', 'Teslim Alırken (Kiracı Yükledi)'), ('return', 'İade Ederken (Satıcı Yükledi)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Mesaj'), ('booking', 'Kiralama Talebi'), ('wallet', 'Cüzdan ve Finans'), ('system', 'İptal ve Sistem'), ('review', 'Değerlendirme')], max_length=20),
        ),
    ]
