# Generated by Django 6.0.6 on 2026-07-29 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Satıcıya gösterilecek ilanın kaldırılma/banlanma sebebi.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Kullanıcının şikayetine eklediği kanıt görseli.', null=True, upload_to='reports/proofs/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='banned_until',
            field=models.DateTimeField(blank=True, help_text='İlanın banının açılacağı tarih.', null=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('billing', 'Ödeme ve Bakiye İşlemleri'), ('account', 'Hesap ve Profil İşlemleri'), ('item_issue', 'İlan ve Kiralama Sorunları'), ('technical', 'Sistem ve Teknik Sorunlar'), ('other', 'Diğer')], max_length=20)),
                ('subject', models.CharField(help_text='Kullanıcının yazdığı kısa konu başlığı', max_length=255)),
                ('description', models.TextField(help_text='Sorunun detaylı açıklaması')),
                ('attachment', models.ImageField(blank=True, help_text='Kullanıcının sorunuyla ilgili eklediği görsel.', null=True, upload_to='tickets/attachments/')),
                ('status', models.CharField(choices=[('open', 'Açık (Bekliyor)'), ('in_progress', 'İnceleniyor'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
