# Generated by Django 6.0.6 on 2026-07-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='iban',
            field=models.CharField(blank=True, help_text='TR ile başlayan 26 haneli IBAN', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sub_merchant_key',
            field=models.CharField(blank=True, help_text='İyzico Alt Üye İşyeri Anahtarı', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tckn',
            field=models.CharField(blank=True, help_text='Satıcı kayıtları için zorunlu TC Kimlik No', max_length=11, null=True),
        ),
    ]
