# Generated by Django 6.0.6 on 2026-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Kullanıcıya gösterilecek banlanma sebebi/mesajı.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='banned_until',
            field=models.DateTimeField(blank=True, help_text='Kullanıcının banının açılacağı tarih. Süresiz ban için çok ileri bir tarih verilebilir.', null=True),
        ),
    ]
