"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3aoqpp_53bwr6h)!^ivl7(^mzn-544672zbk+9$@e6)*r2yl)='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "unfold",
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'items',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = "core.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# CORS Ayarları
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Custom User Modeli Tanımı
AUTH_USER_MODEL = 'users.CustomUser'

# Endüstri Standardı Çift Giriş Destekleyen Kimlik Doğrulama Katmanı
AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameModelBackend',  # Özel yazdığımız akıllı sınıf
    'django.contrib.auth.backends.ModelBackend',   # Django'nun varsayılan doğrulaması
]

# Django REST Framework & JWT Ayarları
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}


# E-Posta Gönderim Ayarları (Geliştirme Aşaması)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Canlıda gerçek mail göndermek istediğinde burayı açacaksın:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'

import os

# Medya dosyalarının (yüklenen fotoğrafların) tutulacağı klasör ayarları
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

from datetime import timedelta

# Django REST Framework & JWT Süre Uzatma Ayarları
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),      # Access token artık 24 saat geçerli
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),    # Refresh token 30 gün geçerli
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}

UNFOLD = {
    "SITE_TITLE": "RentCircle",
    "SITE_HEADER": "RentCircle Yönetim Paneli",
    # Mavi tonlarında modern bir ana renk tanımlaması
    "COLORS": {
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6", 
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
            "950": "#172554",
        },
    },
    # Özel Sol Menü (Sidebar) Yapılandırması
    "SIDEBAR": {
        "show_search": True, # Sol üste arama çubuğu ekler
        "show_all_applications": True,
        "navigation": [
            {
                "title": "İlan ve Kiralama Yönetimi",
                "separator": True,
                "items": [
                    {"title": "Kiralama İşlemleri", "icon": "handshake", "link": "/admin/items/booking/"},
                    {"title": "Aktif İlanlar", "icon": "inventory_2", "link": "/admin/items/item/"},
                    {"title": "Kategoriler", "icon": "category", "link": "/admin/items/category/"},
                ],
            },
            {
                "title": "Kullanıcı Yönetimi",
                "separator": True,
                "items": [
                    {"title": "Tüm Kullanıcılar", "icon": "people", "link": "/admin/users/customuser/"},
                    {"title": "Yetki Grupları", "icon": "admin_panel_settings", "link": "/admin/auth/group/"},
                ],
            },
            {
                "title": "İletişim & Denetim",
                "separator": True,
                "items": [
                    {"title": "Mesajlaşmalar", "icon": "forum", "link": "/admin/items/conversation/"},
                ],
            },
        ],
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Kendi bilgilerini buraya gir
EMAIL_HOST_USER = 'ibrahimbbcn1907@gmail.com' # Şifresini aldığın Gmail adresin
EMAIL_HOST_PASSWORD = 'tasm xbax hhfg xsca' # Örn: 'abcd efgh ijkl mnop' boşluklu veya boşluksuz olabilir

# Default gönderici ismi (Opsiyonel ama maillerin spama düşmesini azaltır)
DEFAULT_FROM_EMAIL = 'RentCircle <ibrahimbbcn1907@gmail.com>'


# IYZICO AYARLARI
IYZICO_API_KEY = 'sandbox-Ft87nBAz0FttTk27CVQAkPl8kLYv1Mok'
IYZICO_SECRET_KEY = 'sandbox-vq6GaNaMITifE38xOInobhdK25VB4MnI'
IYZICO_BASE_URL = 'sandbox-api.iyzipay.com'

# ==========================================
# WEBSOCKET / CHANNELS / UPSTASH REDIS
# ==========================================

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "address": "rediss://default:gQAAAAAAAqtvAAIgcDI1ZTUwZDhjZWRjNmU0MjlkOTJlZGM5ODFiYjVmZjBlZg@legal-mudfish-174959.upstash.io:6379",
                    "ssl_cert_reqs": None,
                    "socket_connect_timeout": 10,
                    "socket_timeout": 30,
                }
            ],
        },
    },
}