# Generated by Django 6.0.6 on 2026-07-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='handover_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Onay Bekliyor (Para Havuzda)'), ('approved', 'Onaylandı (Bekleniyor)'), ('active', 'Kirada (Teslim Edildi)'), ('completed', 'Tamamlandı (İade Edildi)'), ('rejected', 'Reddedildi / İptal'), ('disputed', 'Uyuşmazlık (Sorun Var)')], default='pending_approval', max_length=20),
        ),
    ]
