# Generated by Django 6.0.6 on 2026-07-07 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_booking_dispute_reason_booking_handover_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='handover_photos',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_photos',
        ),
        migrations.CreateModel(
            name='BookingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='booking_evidence/')),
                ('image_type', models.CharField(choices=[('handover', 'Teslimat Anı'), ('return', 'İade Anı')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.booking')),
            ],
        ),
    ]
