# Generated by Django 6.0.6 on 2026-07-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_booking_conversation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deposit_transaction_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_transaction_id',
        ),
    ]
