# Generated by Django 6.0.6 on 2026-07-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_message_is_location_share_message_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
    ]
