# Generated by Django 6.0.6 on 2026-08-04 10:13

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_rename_owner_review_target_user_alter_review_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingimage',
            name='image',
            field=models.ImageField(upload_to='booking_evidence/'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Kullanıcının şikayetine eklediği kanıt görseli.', null=True, upload_to='reports/proofs/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.ImageField(blank=True, help_text='Kullanıcının sorunuyla ilgili eklediği görsel.', null=True, upload_to='tickets/attachments/'),
        ),
    ]
