"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 🎯 .env DOSYASINI YÜKLE
load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "daphne",
    "channels",
    "unfold",
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'items',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = "core.asgi.application"

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'tr'
TIME_ZONE = 'Europe/Istanbul'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'

# CORS Ayarları
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Custom User Modeli Tanımı
AUTH_USER_MODEL = 'users.CustomUser'


AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameModelBackend', 
    'django.contrib.auth.backends.ModelBackend',
]

#  DRF VE RATE LIMITING (HIZ SINIRLARI)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',      # Kayıtsız ziyaretçi günde en fazla 100 API isteği atabilir
        'user': '1000/day',     # Giriş yapmış kullanıcı günde en fazla 1000 API isteği atabilir
        'login_attempts': '5/min', # Brute-force Koruması: Saniyede 1 şifre deneyen botu kilitler (5 deneme/dakika)
        'register_attempts': '3/hour', # Bot hesap oluşturma (Spam) Koruması
        'password_reset': '3/hour',    # Şifre Sıfırlama Spam Koruması
    },
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==========================================
# 🛡️ GÜVENLİK ZIRHI: JWT TOKEN AYARLARI
# ==========================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15), # 👈 Güvenlik standartları gereği 15 dakikaya indirildi
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,          # 🎯 YENİ: Her token yenilendiğinde eskisini çöpe at (Rotasyon)
    'BLACKLIST_AFTER_ROTATION': True,       # 🎯 YENİ: Eski ve çalınan tokenları Kara Listeye al
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}

UNFOLD = {
    "SITE_TITLE": "RentCircle",
    "SITE_HEADER": "RentCircle Yönetim Paneli",
    "COLORS": {
        "primary": {
            "50": "#eff6ff", "100": "#dbeafe", "200": "#bfdbfe", "300": "#93c5fd",
            "400": "#60a5fa", "500": "#3b82f6", "600": "#2563eb", "700": "#1d4ed8",
            "800": "#1e40af", "900": "#1e3a8a", "950": "#172554",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "İlan ve Kiralama Yönetimi",
                "separator": True,
                "items": [
                    {"title": "Kiralama İşlemleri", "icon": "handshake", "link": "/admin/items/booking/"},
                    {"title": "Aktif İlanlar", "icon": "inventory_2", "link": "/admin/items/item/"},
                    {"title": "Kategoriler", "icon": "category", "link": "/admin/items/category/"},
                ],
            },
            {
                "title": "Kullanıcı Yönetimi",
                "separator": True,
                "items": [
                    {"title": "Tüm Kullanıcılar", "icon": "people", "link": "/admin/users/customuser/"},
                    {"title": "Yetki Grupları", "icon": "admin_panel_settings", "link": "/admin/auth/group/"},
                ],
            },
            {
                "title": "İletişim & Denetim",
                "separator": True,
                "items": [
                    {"title": "Mesajlaşmalar", "icon": "forum", "link": "/admin/items/conversation/"},
                ],
            },
        ],
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'RentCircle <' + os.getenv('EMAIL_HOST_USER', '') + '>'

IYZICO_API_KEY = os.getenv('IYZICO_API_KEY')
IYZICO_SECRET_KEY = os.getenv('IYZICO_SECRET_KEY')
IYZICO_BASE_URL = 'sandbox-api.iyzipay.com'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "address": os.getenv('REDIS_URL'),
                    "ssl_cert_reqs": None,
                    "socket_connect_timeout": 10,
                    "socket_timeout": 30,
                }
            ],
        },
    },
}